// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function Greet() {
  return window['go']['main']['App']['Greet']();
}

export function NewTodo(arg1, arg2) {
  return window['go']['main']['App']['NewTodo'](arg1, arg2);
}
