// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusicList() {
  return window['go']['main']['MusicList']['GetMusicList']();
}

export function GetMusicListFromLocalFiles(arg1) {
  return window['go']['main']['MusicList']['GetMusicListFromLocalFiles'](arg1);
}

export function Play(arg1) {
  return window['go']['main']['MusicList']['Play'](arg1);
}

export function SaveMusicListToFile() {
  return window['go']['main']['MusicList']['SaveMusicListToFile']();
}
