// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMusicList():Promise<string>;

export function GetMusicListFromLocalFiles(arg1:Array<string>):Promise<string>;

export function SaveMusicListToFile():Promise<void>;
