// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTodo(arg1:number):Promise<string>;

export function GetTodos():Promise<string>;

export function NewTodo(arg1:string,arg2:number):Promise<string>;

export function SaveTodos():Promise<void>;

export function UpdateTodo(arg1:number,arg2:boolean,arg3:number):Promise<string>;
