// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTodo(arg1) {
  return window['go']['main']['Todos']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['Todos']['GetTodos']();
}

export function NewTodo(arg1, arg2) {
  return window['go']['main']['Todos']['NewTodo'](arg1, arg2);
}

export function SaveTodos() {
  return window['go']['main']['Todos']['SaveTodos']();
}

export function UpdateTodo(arg1, arg2, arg3) {
  return window['go']['main']['Todos']['UpdateTodo'](arg1, arg2, arg3);
}
