// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTodos() {
  return window['go']['main']['Todos']['GetTodos']();
}

export function NewTodo(arg1, arg2) {
  return window['go']['main']['Todos']['NewTodo'](arg1, arg2);
}
